# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: titonobre/publishing-tools:latest

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run generate
          - lftp -e 'mirror --delete --skip-noaccess --exclude=.ftpquota --reverse --use-pget-n=5 --parallel=5 dist/ /; exit' --user $DEPLOY_FTP_USER --password $DEPLOY_FTP_PASS $DEPLOY_FTP_SERVER
